networks:
  db:
    driver: bridge
services:
  app:
    image: amazoncorretto:17-alpine-jdk
    working_dir: /app2
    command: ./mvnw spring-boot:run
    ports:
      - 8082:8082

    volumes:
      - '.:/app2'
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    networks:
      - db
