networks:
  app_network:
    driver: bridge
services:
  rabbitmq:
    image: rabbitmq:3.13-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - app_network
  app:
    image: amazoncorretto:17-alpine-jdk
    working_dir: /app2
    command: ./mvnw spring-boot:run
    ports:
      - 8082:8082

    volumes:
      - '.:/app2'
    depends_on:
      - rabbitmq
    networks:
      - app_network

